name: CI — Front Angular

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build, Lint & Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./murmure-aurea

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            murmure-aurea/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('murmure-aurea/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build production bundle
        run: npm run build -- --configuration=production
